build:
    tests:
        override:
            -
                command: "phpunit --log-junit 'unitreport.xml' --coverage-clover 'clover.xml'"
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
filter:
    paths:
        - 'public/*'
    excluded_paths:
        - 'config/*'
checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        optional_parameters_at_the_end: true
        no_new_line_at_end_of_file: true
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true

coding_style:
    php:
        spaces:
            around_operators:
                equality: false
                concatenation: false
