language: php

php:
  - 5.3
  - 5.4
  - 5.6
  - hhvm

env:
  - DB=postgres

before_install:
  - ./composer.phar self-update
  - ./composer.phar install --prefer-source --no-interaction --dev

before_script:
  - psql -c 'create database bareos;' -U postgres
  - psql bareos < tests/travis/pgsql/make_tables.sql -U postgres
  - psql bareos < tests/travis/pgsql/grant_privileges.sql -U postgres
  - tests/travis/config_db.sh

branches:
  only:
    - master

script: phpunit --log-junit 'unitreport.xml' --coverage-clover 'clover.xml'

after_script:

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
    email: false
    on_success: never
    on_failure: always
